### ISSUE TITLE
App crash when click the button ("rate the app")

### ISSUE THREAD

**Issue by androidAppGuard** [yuriykulikov/AlarmClock#451]
### We found a crash when testing the app, and the environment is as follows:
```
App version: r22
Android version: 6.0
Device: Nexux_5X
```
### The steps to reproduce:
![4_AlarmClock_ActivityNotFoundException.gif](https://s2.loli.net/2022/05/12/n2vkSdxz5AWRBHm.gif)
### The Crash log is as follows:
```
05-12 08:29:03.479 10526-10526/com.better.alarm E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.better.alarm, PID: 10526
    android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=market://details?id=com.better.alarm }
        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1798)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1512)
        at android.app.Activity.startActivityForResult(Activity.java:3917)
        at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)
        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:67)
        at android.app.Activity.startActivityForResult(Activity.java:3877)
        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:720)
        at android.app.Activity.startActivity(Activity.java:4200)
        at android.app.Activity.startActivity(Activity.java:4168)
        at com.better.alarm.presenter.ActionBarHandler$3.onClick(ActionBarHandler.java:156)
        at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:163)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by yuriykulikov** [comment]
This is an old version. What version are you testing?

**Comment by androidAppGuard** [comment]
oh, sorry, I have entered the wrong version information, the version of the app under testing is 0.40.

**Comment by androidAppGuard** [comment]
oh, I have entered the wrong version information, the version of app under testing is 3.02.02.

**Comment by yuriykulikov** [comment]
Migrate to https://developer.android.com/guide/playcore/in-app-review/kotlin-java

**Comment by androidAppGuard** [comment]
ok, thanks!
