### ISSUE TITLE
Crash when "RATE THE APP" in v3.10.10

### ISSUE THREAD

**Issue by Kobayashi-996** [yuriykulikov/AlarmClock#500]
## Describe the bug
The app crashes when clicking the "RATE THE APP", guess this may be because the phone doesn't have a play store?

## Environment
**Android:** Android 9.0
**App Version:** 3.10.10

## To Reproduce
Describe the steps to reproduce the behavior:
1. Open the app
2. Open "More options"
3. Click "Say thanks"
4. Click "RATE THE APP"
Then the app crashes.

## Expected and observed behavior
Open the play store or ask the user to install a play store, instead of crashing.

## ScreenRecord

https://user-images.githubusercontent.com/120108516/210235728-93500e87-fdde-40c2-ae04-382f02c77733.mp4

## Logcat
FATAL EXCEPTION: main
    Process: com.better.alarm, PID: 22647
    android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=market://details?id=com.better.alarm }
        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2007)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1673)
        at android.app.Activity.startActivityForResult(Activity.java:4586)
        at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:597)
        at android.app.Activity.startActivityForResult(Activity.java:4544)
        at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:583)
        at android.app.Activity.startActivity(Activity.java:4905)
        at android.app.Activity.startActivity(Activity.java:4873)
        at com.better.alarm.presenter.ActionBarHandler.showSayThanks$lambda-9$lambda-8(ActionBarHandler.kt:151)
        at com.better.alarm.presenter.ActionBarHandler.$r8$lambda$Qg8_Wljd5HrGDTXybHJl9cItrHs(Unknown Source:0)
        at com.better.alarm.presenter.ActionBarHandler$$ExternalSyntheticLambda5.onClick(Unknown Source:2)
        at android.view.View.performClick(View.java:6597)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25885)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by yuriykulikov** [comment]
Hello,
yes, this is the reason, but the app probably still should't crash.
