### ISSUE TITLE
Met with service failure and crashed

### ISSUE THREAD

**Issue by Kobayashi-996** [yuriykulikov/AlarmClock#501]
## Describe the bug
I have met with this several times.
I tried to reproduce but failed.
The only thing I have is the logcat, hope the info could help.

## Environment
Android: Android 9.0
App Version: 3.11.00 with the latest commit

## Logcat
01-01 13:24:51.609 27187 27187 E AndroidRuntime: FATAL EXCEPTION: main
01-01 13:24:51.609 27187 27187 E AndroidRuntime: Process: com.better.alarm.debug, PID: 27187
01-01 13:24:51.609 27187 27187 E AndroidRuntime: java.lang.RuntimeException: Unable to start service com.better.alarm.background.AlertServiceWrapper@a3edc9 with Intent { act=com.better.alarm.debug.ALARM_DISMISS cmp=com.better.alarm.debug/com.better.alarm.background.AlertServiceWrapper (has extras) }: java.lang.IllegalStateException: First event must be AlarmEvent or PrealarmEvent, but was DismissEvent(id=3, actions=com.better.alarm.debug.ALARM_DISMISS)
01-01 13:24:51.609 27187 27187 E AndroidRuntime: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3686)
01-01 13:24:51.609 27187 27187 E AndroidRuntime: 	at android.app.ActivityThread.access$1600(ActivityThread.java:199)
01-01 13:24:51.609 27187 27187 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1681)
01-01 13:24:51.609 27187 27187 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-01 13:24:51.609 27187 27187 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
01-01 13:24:51.609 27187 27187 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6669)
01-01 13:24:51.609 27187 27187 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-01 13:24:51.609 27187 27187 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
01-01 13:24:51.609 27187 27187 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
01-01 13:24:51.609 27187 27187 E AndroidRuntime: Caused by: java.lang.IllegalStateException: First event must be AlarmEvent or PrealarmEvent, but was DismissEvent(id=3, actions=com.better.alarm.debug.ALARM_DISMISS)
01-01 13:24:51.609 27187 27187 E AndroidRuntime: 	at com.better.alarm.background.AlertService.stateValid(AlertService.kt:146)
01-01 13:24:51.609 27187 27187 E AndroidRuntime: 	at com.better.alarm.background.AlertService.onStartCommand(AlertService.kt:121)
01-01 13:24:51.609 27187 27187 E AndroidRuntime: 	at com.better.alarm.background.AlertServiceWrapper.onStartCommand(AlertServiceWrapper.kt:203)
01-01 13:24:51.609 27187 27187 E AndroidRuntime: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3667)
01-01 13:24:51.609 27187 27187 E AndroidRuntime: 	... 8 more

**Comment by yuriykulikov** [comment]
Yeah, I am observing there too, sometimes. This only happens in debug builds though.
